In [10]:
import numpy as np

def rotate(A):
    rotated_A = np.array(A).T.tolist()
    for i in range(len(A[0])):
        for j in range(len(A)):
            rotated_A[i][j] = A[j][-(i+1)]
    return rotated_A

def reset(A):
    _A = A.copy()
    x = list(_A.pop(0))
    while _A:
        _A = rotate(_A)
        x += _A.pop(0)
    return np.array(x).reshape(np.array(A).shape)
    

test = [[1, 2, 3, 4, 5], [16, 17, 18, 19, 6], [15, 24, 25, 20, 7], [14, 23, 22, 21, 8], [13, 12, 11, 10, 9]]
print(reset(test))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
